name: CI-without-cache

on:
  workflow_dispatch:
    inputs:
      Name:   
        required: true
        default: 'Re-run the workflow'
      Description:
        default: ''  

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - uses: actions/checkout@v2

      - name: Run unit tests
        run: npm run test:ci
        with: 
          path: .jest-cache
          key: ${{ runner.os }}-jestCache-${{ github.run_id }}

      - name: Install dependencies
        run: npm ci
      
      # Not using incremental build
      - name: Build without Cache
        run: npm run build:noCache
        env:
          EVENT_API_KEY_1: ${{ secrets.EVENT_API_KEY_1 }}
          EVENT_API_KEY_2: ${{ secrets.EVENT_API_KEY_2 }}
          EVENT_ORG_ID_1: ${{ secrets.EVENT_ORG_ID_1 }}
          EVENT_ORG_ID_2: ${{ secrets.EVENT_ORG_ID_2 }}
          GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
          GATSBY_GH_APP_GITALK_ID: ${{ secrets.GATSBY_GH_APP_GITALK_ID }}
          GATSBY_GH_APP_GITALK_SECRET: ${{ secrets.GATSBY_GH_APP_GITALK_SECRET }}
          GATSBY_ENV: ${{ secrets.GATSBY_ENV }}

