name: Test

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: ["**"]
    types:
      [
        opened,
        synchronize,
        reopened
      ]
  workflow_dispatch:
    inputs:
      Name:
        required: true
        default: "Re-run the workflow"
      Description:
        default: ""

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - uses: actions/checkout@v2

      - name: NPM Cache
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-cache-

      - name: Install playwright dependencies
        uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npm ci

      - name: Jest cache
        id: gatsby-jest-cache
        uses: actions/cache@v2
        with:
          path: .jest-cache
          key: ${{ runner.os }}-jestCache-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-jestCache-

      - name: Unit tests
        run: npm run test
      
      - name: E2E tests
        run: npm run test:e2e
